### ISSUE TITLE
when i use LeakCanary , i found volley Response$Listener had leaked?

### ISSUE THREAD

**Issue by jiancao** [mcxiaoke/android-volley#123]
like this:
anonymous class implements com.android.volley.Response$Listener

**Comment by panxw** [comment]
@jiancao 
Maybe like http://blog.csdn.net/jdsjlzx/article/details/8463428

**Comment by chaozaiai** [comment]
how to fix this?

**Comment by jiancao** [comment]
@chaozaiai 
use the latest version

**Comment by huahongyang** [comment]
@jiancao latest version is 1.0.19? how to solve this? i

**Comment by huahongyang** [comment]
1.0.19 is the latest version? how to fix this?

**Comment by huahongyang** [comment]
@jiancao  1.0.19 is the latest version? how to fix this?
