### ISSUE TITLE
Send GET request with params is not working

### ISSUE THREAD

**Issue by brook19** [mcxiaoke/android-volley#128]
String url =  "http://localhost/user"; 
StringRequest stringRequest = new StringRequest(Request.Method.GET, url, responseLis, errorLis) {
            @Override
            protected Map<String, String> getParams() throws AuthFailureError {
                // TODO Auto-generated method stub
                Map<String, String> param = new HashMap<>();
                param.put("action","search");
                param.put("id","1");
                return requestMap;
            }
        };

When send the request, the url can't auto convert to "http://localhost/user?action=search&id=1".

Just like KJFrameForAndroid send GET request.

**Comment by 3pehrbehroozi** [comment]
Hi.
I don't think that should call an issue, cause we should handle URL parameters ourselves but it would be nice to put such capability

**Comment by brook19** [comment]
Ok!
