### ISSUE TITLE
Mention official volley library in README

### ISSUE THREAD

**Issue by samtstern** [mcxiaoke/android-volley#144]
Volley is now hosted by the Android Open Source Project on jCenter, you can get it with the following line:

`compile 'com.android.volley:volley:1.0.0`

This repository is, and has been for a long time, the most popular mirror of Volley.  Now that there is an official version, could you mention it in the README file so that those who end up on this page are aware of the official version?

**Comment by mcxiaoke** [comment]
done

**Comment by samtstern** [comment]
@mcxiaoke thank you!

I know that over the years you have taken in patches to Volley through this repository.  If you'd like to discuss putting some of them into AOSP let me know.  Your maintenance of this repo over the years is very much appreciated and we'd value your input.
