### ISSUE TITLE
NetworkImageView setBitmap gets overriden on layout

### ISSUE THREAD

**Issue by spawrks** [mcxiaoke/android-volley#33]
This is for the Volley team, not your fork, but when looking at the overhead for submitting a patch to Google my eyes just kinda of glazed over so I thought I would put this somewhere it might be useful.

If you're trying to do this, which many people are:

```java
imageLoader.get(data.getImageUrl(), new ImageLoader.ImageListener(){
            @Override
            public void onResponse(ImageLoader.ImageContainer response, boolean isImmediate) {
                Log.e("TAG",response.toString());
                if(response.getBitmap() != null){
                    Bitmap b = response.getBitmap();
                    p.imageView.setImageBitmap(response.getBitmap());
                }
            }

            @Override
            public void onErrorResponse(VolleyError error) {

            }
        });
```

and imageView is a NetworkImageView, the bitmap will trigger an onLayout change and consequently the image will be nulled out on the view.  NetworkImageView's should stop trying to get data or changing their content is someone manually is using them as an ImageView. 

For those of you who have come across this, you can always just set the url to be something bad for the NetworkImageView (like "NONETWORK") and it will gracefully error out and you can use it manually, but it seems like if you're going to extend from ImageView you shouldn't break the parent class's use cases.

**Comment by mcxiaoke** [comment]
close
