### ISSUE TITLE
Feature Request: Request Identifier

### ISSUE THREAD

**Issue by pirdaddigiflare** [mcxiaoke/android-volley#36]
I've made a feature request on the main google groups but I would like to post it here too to see if it's a possibility. Link to the post: https://groups.google.com/d/topic/volley-users/S3pCu7kKMTo/discussion.

Basically, I would like to be able to get an id back as a parameter on the success/failure callback functions.

**Comment by mcxiaoke** [comment]
done at 81b2ea1ac9b8cbe64f7097c70b2f034f8683be1e in v1.0.15
