### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by espiegel** [mcxiaoke/android-volley#37]
I'm getting this error sometimes which causes my application to crash:

java.lang.NegativeArraySizeException: -450
            at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:322)
            at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:118)
            at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)

**Comment by mcxiaoke** [comment]
fixed in https://github.com/mcxiaoke/android-volley/pull/38

**Comment by ValleZ** [comment]
is this in 1.0.15?

**Comment by mcxiaoke** [comment]
@ValleZ No, I will release a new version in two days.

**Comment by mcxiaoke** [comment]
@ValleZ not yet, I will publish a new version in this week.

**Comment by moradgholi** [comment]
@mcxiaoke haven't you release an update on this ?

**Comment by mcxiaoke** [comment]
@moradgholi released today

**Comment by binqiangsun** [comment]
Is this only github updated. I found these codes are not in the android / platform/frameworks/volley / android-5.1.1_r4  of google code?

**Comment by joebowbeer** [comment]
I think this is another symptom of #61 (OutOfMemoryError) and both of these are caused by problems reading the header.

**Comment by agozie** [comment]
I got this today.

Exception java.lang.NegativeArraySizeException: -824
com.android.volley.toolbox.DiskBasedCache.streamToBytes (DiskBasedCache.java:323)
com.android.volley.toolbox.DiskBasedCache.get (DiskBasedCache.java:119)
com.android.volley.CacheDispatcher.run (CacheDispatcher.java:100)

**Comment by abhaymaniyar** [comment]
I got this few days ago:

Fatal Exception: java.lang.NegativeArraySizeException: -1362
       at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:323)
       at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:119)
       at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)

**Comment by joebowbeer** [comment]
This should now be fixed in the 1.1.1-SNAPSHOT build of https://github.com/google/volley
