### ISSUE TITLE
RequestQueue does not clear original url key from mWaitingRequests on redirects

### ISSUE THREAD

**Issue by gengrui1983** [mcxiaoke/android-volley#40]
In the case of redirects when requesting images, when you want to fetch the same image again, however the size of your NetworkImageView is different than in the first request, the image is not found. The server request is not fired either, because `mWaitingRequests` contains the original URL and hence the new request is ignored by Volley (the request queued forever).

Suggested fix is in `RequestQueue.finish(Request<T> request)` make the following change:

    //String cacheKey = request.getCacheKey();
    String originalKey = request.getOriginUrl();
    String cacheKey = request.getCacheKey();
    Queue<Request<?>> waitingRequests;
    if (!originalKey.equals(cacheKey)) {
        waitingRequests = mWaitingRequests.remove(originalKey);
    }

In order to test, you can create an app with a `NetworkImageView` that requests an image in (lets say) 50dpx50dp (`NetworkImageViews` size) and then on click of a button, an other `NetworkImageView` requests the same image in 100dpx100dp.

You can use the URL below to test which redirects to the actual image.
http://graph.facebook.com/592371158/picture

**Comment by mcxiaoke** [comment]
fixed in 0aa7873db1048c41b279e4f216e4cf2ee35d0802
