### ISSUE TITLE
JsonArrayRequest with Post Parameter

### ISSUE THREAD

**Issue by legalimpurity** [mcxiaoke/android-volley#44]
Hello,

JsonArrayRequest does not accepts JSONObject as post object.

I found a solution to add this here in Volley Library.

http://stackoverflow.com/questions/18048806/volley-sending-a-post-request-using-jsonarrayrequest

But, I cannot edit gradle file in Android Studio.
Please add this to the code of possible.
Thank You

**Comment by legalimpurity** [comment]
Hello,

What you commited was 

  public JsonArrayRequest(int method, String url, JSONArray jsonRequest, 
            Listener<JSONArray> listener, ErrorListener errorListener) {
        super(method, url, (jsonRequest == null) ? null : jsonRequest.toString(), listener,
                errorListener);
    }


can you please also add  


  public JsonArrayRequest(int method, String url, JSONObject jsonRequest, 
            Listener<JSONArray> listener, ErrorListener errorListener) {
        super(method, url, (jsonRequest == null) ? null : jsonRequest.toString(), listener,
                errorListener);
    }

What I pass to JSONObject not array
Thank You

**Comment by mcxiaoke** [comment]
fixed at 06335260f0fac87890d1fcd9f5cbfc53daaf2d39 and release at v1.0.14
