### ISSUE TITLE
JsonObjectRequest does not take null for jsonRequest/requestBody

### ISSUE THREAD

**Issue by HPIWicket** [mcxiaoke/android-volley#45]
It is not possible to to pass null into the constructor (when using another Method than GET) of the JsonObjectRequest since the new constructors have been added, because multiple constructors apply. Can another constructor for an empty request body be added?

**Comment by mcxiaoke** [comment]
fixed by cd543ea8971138bc94f744ef1679370f39117927 ,released at 1.0.15
