### ISSUE TITLE
Image disappears in CursorAdapter

### ISSUE THREAD

**Issue by buneme** [mcxiaoke/android-volley#49]
I'm using volley to load images in my cursor adapter. The images successfully load, however, when I scroll away, and scroll back up the image disappears[1]

Here is the relevant code:

In the array initializer:

    mImageLoader = MyApplication.getInstance().getImageLoader();

And in my bindView method:

    storyImage.setImageUrl(imageURL, mImageLoader);

The mImageLoader initialization references to MyApplication.class, which can be found here[2]

  [1]: https://vid.me/48vf "the image disappears"
  [2]: https://gist.github.com/buneme/10ffb5ede0b4ad8b47db

**Comment by mcxiaoke** [comment]
it's not related with volley.
