### ISSUE TITLE
VolleyError is not Serializable

### ISSUE THREAD

**Issue by minarofaeil** [mcxiaoke/android-volley#53]
Volley class com.android.volley.VolleyError extends java.lang.Exception. Exception class is Serializable and so VolleyError is. But VolleyError contains a NetworkResponse instance which is not Serializable.

Serializing a VolleyError instance fails with a NotSerializableException.

**Comment by mcxiaoke** [comment]
fixed in 4012176f203cf33cd2b8ee8305a3eac4afd6c393
