### ISSUE TITLE
Why is Volley calling https://safebrowsing.google.com?

### ISSUE THREAD

**Issue by grushy** [mcxiaoke/android-volley#56]
Library used:

    compile 'com.mcxiaoke.volley:library:1.0.15'

Version used:

-----log------
D/Finsky  (19660): [1] PackageVerificationReceiver.onReceive: Verification requested, id = 303
D/Finsky  (19660): [1] PackageVerificationService.cancelVerificationIntent: Cancel active verification id=303
D/Finsky  (19660): [1] 3.onErrorResponse: Verification id=303 error response com.android.volley.TimeoutError
D/Volley  (19660): [1] Request.finish: 10091 ms: [ ] https://safebrowsing.google.com/safebrowsing/clientreport/download 0xc9395b26 NORMAL 42

**Comment by mcxiaoke** [comment]
@grushy Finsky is the alias of Play Store app, the log is from volley in Android system using by Play Store, not from this volley library.

**Comment by grushy** [comment]
thanks
