### ISSUE TITLE
Anyone knows how to pass params to JsonObjectRequest in the newest version

### ISSUE THREAD

**Issue by binqiangsun** [mcxiaoke/android-volley#57]
As an old version of volley.jar. Other college made it and we pass params by following method:
 @Override
            public byte[] getBody() {
                if (params != null && params.size() > 0) {
                    return encodeParameters(params, getParamsEncoding());
                }
                return null;
            }

But we need to update volley, and find that this method was changed to private.

I also found that to override the method of getParams(), which did not work for me.  the Method getBody of JsonObjectRequest is as following:

public byte[] getBody() {
        try {
            return mRequestBody == null ? null : mRequestBody.getBytes(PROTOCOL_CHARSET);
        } catch (UnsupportedEncodingException uee) {
            VolleyLog.wtf("Unsupported Encoding while trying to get the bytes of %s using %s",
                    mRequestBody, PROTOCOL_CHARSET);
            return null;
        }
    }

so I cannot pass the params now.

**Comment by mcxiaoke** [comment]
close this.
