### ISSUE TITLE
Anyone knows how to pass params to JsonObjectReques in the newest version.

### ISSUE THREAD

**Issue by binqiangsun** [mcxiaoke/android-volley#58]
As an old version of volley.jar.  we pass params by following method:
 @Override
            public byte[] getBody() {
                if (params != null && params.size() > 0) {
                    return encodeParameters(params, getParamsEncoding());
                }
                return null;
            }

But we need to update volley, and find that this method was changed to private.

I also found that to override the method of getParams(), which did not work for me.  the Method getBody of JsonObjectRequest is as following:

public byte[] getBody() {
        try {
            return mRequestBody == null ? null : mRequestBody.getBytes(PROTOCOL_CHARSET);
        } catch (UnsupportedEncodingException uee) {
            VolleyLog.wtf("Unsupported Encoding while trying to get the bytes of %s using %s",
                    mRequestBody, PROTOCOL_CHARSET);
            return null;
        }
    }

so I cannot pass the params now.

**Comment by Cmdmac** [comment]
hello,the newest version volley JsonObjectRequest use getBody as post request body and the content-type is application/json,if you want to post key=value& in the body,use can pass key=value string in the constructor and the content-type use application/x-www-form-urlencoded ; )
@Override
public String getBodyContentType() {
    if (getMethod() == Method.POST) {
        return "application/x-www-form-urlencoded";
    }
    return super.getBodyContentType();
}

**Comment by mcxiaoke** [comment]
close this.
