### ISSUE TITLE
Application crashes on HTTP 404 status code 

### ISSUE THREAD

**Issue by waqary705** [mcxiaoke/android-volley#63]
when server return HTTP status code 404 then application crashes.
 new Response.ErrorListener() {

					@Override
					public void onErrorResponse(VolleyError error) {
						Log.e(TAG, "Registration Error: " + error.getMessage());
						Toast.makeText(getApplicationContext(),
								error.getMessage(), Toast.LENGTH_LONG).show();
						hideDialog();
					}
				})
in this method and return null Toast

**Comment by mcxiaoke** [comment]
check Activity.isFinishing() or Fragment.isAdded()

**Comment by waqary705** [comment]
Its okie but i don't want to close activity or fragment instead i want to get  Header's text status code from server
