### ISSUE TITLE
jar file of project

### ISSUE THREAD

**Issue by voltan** [mcxiaoke/android-volley#66]
Hello

I need jar file of this project for us on my app on , at this moment I use eclipse and cant move project to android studio. any link for download jar file?

thanks

**Comment by BraveAction** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.mcxiaoke.volley%22

**Comment by mcxiaoke** [comment]
@voltan https://repo1.maven.org/maven2/com/mcxiaoke/volley/library/1.0.16/library-1.0.16.jar

**Comment by voltan** [comment]
Thank you very much
@BraveAction @mcxiaoke
