### ISSUE TITLE
Are you aware that even Google use your fork?

### ISSUE THREAD

**Issue by redwarp** [mcxiaoke/android-volley#71]
They announced Eddystone the other day, and in the sample app, in the gradle configuration file: https://github.com/google/beacon-platform/blob/master/samples/android/BeaconServiceDemoApp/app/build.gradle

Keep up the good work!

**Comment by espiegel** [comment]
The power of the open source community :)

**Comment by mcxiaoke** [comment]
thanks , I'm working on it.
