### ISSUE TITLE
Post  Image to my Server

### ISSUE THREAD

**Issue by MrThiago** [mcxiaoke/android-volley#72]
Hello, Is there a simple easy and reliable  implement to send Image or a File to my server via POST ?

All the resources online, say,that volley does not include MultiPartJSONRequest:

But all the sample I tried from stackoverflow, does not work.

I just want to take a photo from the camera and post it to my server.

**Comment by mcxiaoke** [comment]
volley does not support multipart by default, you can check other libraries.

**Comment by BraveAction** [comment]
@MrThiago !
I use this do my job:

  ByteArrayOutputStream out = new ByteArrayOutputStream(1000);
  boolean flags = newBitmap.compress(Bitmap.CompressFormat.JPEG, 50, out);
  byte[] bytes= Base64.encode(out.toByteArray(), Base64.NO_WRAP);
  String imageString = new String(bytes, "GBK");

that you can post this string(imageString) to your server;
sorry for my bad English!
