### ISSUE TITLE
volley image cache doed not hit without a netwok

### ISSUE THREAD

**Issue by KingC-usst** [mcxiaoke/android-volley#74]
I achieved L1 and L2 cache in volley(I have tried ImageLoader and NetworkImage)

I get a image url from server like  "http://54.xxx.xxx.xxx:10000/xxx/images/xxx.jpg"

I can't get the image cache  after I kill the progress

But a url like "http://www.example.com/xxx/xxx/xxx.jpg" works

why?

**Comment by mcxiaoke** [comment]
not related with volley
