### ISSUE TITLE
API request sent two times

### ISSUE THREAD

**Issue by joydip1990** [mcxiaoke/android-volley#76]
Server is slow. Volley is sending request two times i.e Its retrying to send request again.

I had solved the problem by overriding  retry policy.

 jsonObjReq.setShouldCache(false);

 jsonObjReq.setRetryPolicy(new DefaultRetryPolicy(
                (int) TimeUnit.SECONDS.toMillis(20),
                DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));

Please resolve this issue.

**Comment by mcxiaoke** [comment]
duplicate of issue #46
