### ISSUE TITLE
Is this repo exact mirror of original Volley?

### ISSUE THREAD

**Issue by gitanuj** [mcxiaoke/android-volley#77]
I found some changes to BasicNetwork.java which are not present in the Volley's original source code at https://android.googlesource.com/platform/frameworks/volley/

**Comment by mcxiaoke** [comment]
@gitanuj not exactly, with some minor bugfix (some pr merged) , see here:  https://github.com/mcxiaoke/android-volley#history

**Comment by mcxiaoke** [comment]
@gitanuj I have updated readme , see [here](https://github.com/mcxiaoke/android-volley/blob/master/README.md#android-volley--)
