### ISSUE TITLE
Volley can't handle "big" json

### ISSUE THREAD

**Issue by ben-j69** [mcxiaoke/android-volley#80]
If you do this request with volley https://maps.googleapis.com/maps/api/directions/json?sensor=true&origin=48.8256676,2.383315000000001&destination=50.6293797,3.0570117&alternatives=true

WIth a StringRequest or JsonRequest, a timeout occurs.

**Comment by sewar** [comment]
I'm facing this issue too, timeout counter should stop when the response is received from server/cache.

**Comment by davidjorgensen** [comment]
actually volley is not meant to be used for large data, and it will perform horribly (or not work properly) when trying.. You are better off using something else when loading huge content.

**Comment by CJstar** [comment]
I agree with @davidjorgensen ,Volley is meant many small requests.

**Comment by mcxiaoke** [comment]
@ben-j69 volley store whole http response contents as byte[] in memory and then convert to String or Json or other type, so it can not handle huge response, you should use okhttp instead.

```java
// in BasicNetwork line 129
responseContents = entityToBytes(httpResponse.getEntity());
```
