### ISSUE TITLE
android Volley delete method, why will send empty parameters?

### ISSUE THREAD

**Issue by DOWONLEE** [mcxiaoke/android-volley#81]
public class HurlStack implements HttpStack {
             break;
         case Method.DELETE:
             connection.setRequestMethod("DELETE");
             addBodyIfExists(connection, request); // we can call addBodyIfExists method 
             break;
         case Method.POST:
             connection.setRequestMethod("POST");

**Comment by mcxiaoke** [comment]
not supported

**Comment by fancysherry** [comment]
why not add this feature to volley?i need to modify some code everytime i want to execute the delete request with params.

when i modify some code,it work well,but i worry my code may have other problem.
