### ISSUE TITLE
Failed to resolve: com.mcxiaoke.volley:library:1.0.18

### ISSUE THREAD

**Issue by uuku** [mcxiaoke/android-volley#84]
I add volley library to my project using Android Studio(gradle version: 2.4), but the gradle complains that `Failed to resolve: com.mcxiaoke.volley:library:1.0.18`. However I change the volley to 1.0.17, it is OK.

**Comment by mcxiaoke** [comment]
@uuku I just test it, no errors, and you can see artifacts are in here [volley](http://search.maven.org/#artifactdetails%7Ccom.mcxiaoke.volley%7Clibrary%7C1.0.18%7Cjar). use `./gradlew clean build --refresh-dependencies` try again?

**Comment by ch-muhammad-adil** [comment]
hey I am facing same issue even i have change the volley to 1.0.17 .. but no luck

**Comment by ch-muhammad-adil** [comment]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_repositoriesCompile'.
   > Could not resolve com.mcxiaoke.volley:library:1.0.18.
     Required by:
         Orient-TV-Guide:app:unspecified
      > Could not HEAD 'https://jcenter.bintray.com/com/mcxiaoke/volley/library/1.0.18/library-1.0.18.pom'.
         > Connection to http://127.0.0.1:8555 refused
      > Could not HEAD 'https://repo1.maven.org/maven2/com/mcxiaoke/volley/library/1.0.18/library-1.0.18.pom'.
         > Connection to http://127.0.0.1:8555 refused

**Comment by ch-muhammad-adil** [comment]
Kindly help me regarding this issue. I have tried everything but all in vein. it has wasted a lot of my time.

**Comment by Senior-JAM** [comment]
I add volley library to my project using Android Studio(Android Studio version: 1.5.1), but the gradle complains that Failed to resolve: com.mcxiaoke.volley:library:1.0.18.
