### ISSUE TITLE
NetworkDispatcher Thread Leak

### ISSUE THREAD

**Issue by f3ist** [mcxiaoke/android-volley#85]
When the NetworkDispatcher is interrupted while doing a request, the exception is swallowed and the thread will wait forever on the blocking queue `take()` method.

**Comment by kennethshackleton** [comment]
There's [this](http://developer.android.com/reference/java/util/concurrent/locks/Condition.html#await()):

> If the current thread: ... has its interrupted status set on entry to this method; ... then `InterruptedException` is thrown and the current thread's interrupted status is cleared.

which may or may not be relevant here.

**Comment by f3ist** [comment]
The would be better than the `take()` method as far as waiting indefinitely, however, the loop is waiting to take a request from the blocking queue for processing, so not sure how you `await()` could be substituted.

**Comment by mcxiaoke** [comment]
fixed in other ways in 1.0.19

**Comment by INRIX-Chris-Feist** [comment]
Still never a good idea to have an infinite wait and generic exception catcher that can take you back to the infinite wait.

**Comment by f3ist** [comment]
Still never a good idea to have an infinite wait and generic exception catcher that can take you back to the infinite wait.

**Comment by chaozaiai** [comment]
![image](https://cloud.githubusercontent.com/assets/8943761/13836132/0e0a7ab0-ec39-11e5-9e2d-e0f547992723.png)
I have this leaked, how avoid these leak??? I need your help.
