### ISSUE TITLE
mErrorListener, mListener should be nulled whenever request is cancelled

### ISSUE THREAD

**Issue by leo524891010** [mcxiaoke/android-volley#93]
Please refer to this link:
https://stackoverflow.com/questions/26599636/should-i-worry-about-memory-leaks-and-using-weakreference-with-volley-in-android#_=_

**Comment by RobertoIDL** [comment]
I've seen the same issue on my code. So far the latest version of Volley still doesn't fix it for me. I'll try to clean the listeners on the cancel method.

**Comment by leo524891010** [comment]
@RobertoIDL  Here is solution for this. Design a subclass which inherits from Request, and define your own errorListener there instead of using the one in Base Class. Then whenever your request finishes, you have full control to clear the errorListener you defined.

**Comment by RobertoIDL** [comment]
Thanks @leo524891010 that's what I've done and it's working fine. Just for the record I've found another potential leak due to the VolleyLog class and the method finalize()

**Comment by mcxiaoke** [comment]
fixed in 1.0.19
