### ISSUE TITLE
BasicNetwork.performRequest: Unexpected response code 502

### ISSUE THREAD

**Issue by ashishsakarkar2020** [mcxiaoke/android-volley#97]
The data fails to load sporadically. However hitting the API again (almost immediately after fail), I get the data. 

The error response is 

BasicNetwork.performRequest: Unexpected response code 502

Note: using same APIs from another server( Mirror) never fails.

**Comment by mcxiaoke** [comment]
it may be caused by your server, not related with volley.

**Comment by ashishsakarkar2020** [comment]
This is the connection time out log...



09-30 12:03:45.909: W/System.err(11229): org.apache.http.conn.ConnectTimeoutException: Connect to /66.96.149.1:80 timed out
09-30 12:03:45.910: W/System.err(11229): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
09-30 12:03:45.911: W/System.err(11229): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
09-30 12:03:45.911: W/System.err(11229): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
09-30 12:03:45.912: W/System.err(11229): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
09-30 12:03:45.912: W/System.err(11229): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
09-30 12:03:45.913: W/System.err(11229): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
09-30 12:03:45.913: W/System.err(11229): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
09-30 12:03:45.913: W/System.err(11229): 	at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
09-30 12:03:45.914: W/System.err(11229): 	at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
09-30 12:03:45.914: W/System.err(11229): 	at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
09-30 12:03:45.915: W/System.err(11229): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
09-30 12:03:45.924: W/System.err(11229): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
09-30 12:03:45.924: W/System.err(11229): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
09-30 12:03:45.927: W/System.err(11229): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
09-30 12:03:45.927: I/SurfaceTextureClient(11229): [STC::queueBuffer] (this:0x5742a5f0) fps:43.60, dur:1009.18, max:49.95, min:6.85
09-30 12:03:45.929: W/System.err(11229): 	at java.lang.Thread.run(Thread.java:838)


09-30 12:03:45.930: E/GetProductListListner(11229):  URL http://www.offerscalling.com/couponAPI/newDealsAPI.php?limit=0
09-30 12:03:46.311: E/GetNeayByStoreTask(11229):  URL http://www.offerscalling.com/couponAPI/storeLocationAPI.php?lat=21.2513844&lng=81.6296413&category=&limit=0&distance=1

09-30 12:03:46.430: E/GetProductListListner(11229):  URL http://www.offerscalling.com/couponAPI/searchProductsAPI.php?search_term=Ritz&cities=0&limit=0
